PACKAGE_NAME="platform-fans-hwmon"
PACKAGE_VERSION="0.2.0"
BUILT_MODULE_NAME[0]="platform_fans_hwmon"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make KERNEL_VERSION=${kernelver}"
CLEAN="make clean KERNEL_VERSION=${kernelver}"
AUTOINSTALL="yes"
