PACKAGE_NAME="intel-nuc-ec-hwmon"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="intel_nuc_ec_hwmon"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
MAKE[0]="make KERNEL_VERSION=${kernelver}"
CLEAN="make KERNEL_VERSION=${kernelver} clean"
